const USER_BOOK_STATUS_CONSTANTS = {
    WANT_TO_READ: 'Want to Read',
    CURRENTLY_READING: 'Currently Reading',
    READ: 'Read',
    NONE: 'None'
};

export const USER_BOOK_STATUS_CONSTANTS_LIST = [USER_BOOK_STATUS_CONSTANTS.CURRENTLY_READING, 
            USER_BOOK_STATUS_CONSTANTS.WANT_TO_READ, USER_BOOK_STATUS_CONSTANTS.READ];

export default USER_BOOK_STATUS_CONSTANTS;