const BOOK_STATUS_CONSTANTS = {
    NONE: 'None',
    WANT_TO_READ: 'Want to Read',
    CURRENTLY_READING: 'Currently Reading',
    READ: 'Read'
}

const BOOK_STATUS_CONSTANTS_NONE = 'NONE';
const BOOK_STATUS_CONSTANTS_WANT_TO_READ = 'Want to Read';
const BOOK_STATUS_CONSTANTS_CURRENTLY_READING = 'Currently Reading';
const BOOK_STATUS_CONSTANTS_READ = 'Read';

module.exports.BOOK_STATUS_CONSTANTS_NONE                   = BOOK_STATUS_CONSTANTS_NONE;
module.exports.BOOK_STATUS_CONSTANTS_WANT_TO_READ           = BOOK_STATUS_CONSTANTS_WANT_TO_READ;
module.exports.BOOK_STATUS_CONSTANTS_CURRENTLY_READING      = BOOK_STATUS_CONSTANTS_CURRENTLY_READING;
module.exports.BOOK_STATUS_CONSTANTS_READ                   = BOOK_STATUS_CONSTANTS_READ;